INSERT INTO SUBSCRIPTIONS (user_id, subscription_tier, price) VALUES
(1, 'Inferno', 19.99),      -- James Sutton
(2, 'Obsidian', 9.99),      -- Max Holloway
(3, 'Crimson', 5.99),       -- Ava Kimura
(4, 'Free', 0.00),          -- Liam Takeda
(5, 'Inferno', 19.99),      -- Sophia Watanabe
(6, 'Obsidian', 9.99),      -- Noah Ishikawa
(7, 'Crimson', 5.99),       -- Emma Hayashi
(8, 'Free', 0.00),          -- Oliver Mori
(9, 'Obsidian', 9.99),      -- Mia Tanaka
(10, 'Inferno', 19.99),     -- Elijah Nakamura
(11, 'Free', 0.00),         -- Isabella Sato
(12, 'Crimson', 5.99),      -- Lucas Akiyama
(13, 'Inferno', 19.99),     -- Amelia Fujimoto
(14, 'Free', 0.00),         -- James Yamamoto
(15, 'Obsidian', 9.99),     -- Charlotte Inoue
(16, 'Inferno', 19.99),     -- Benjamin Kojima
(17, 'Crimson', 5.99),      -- Harper Matsuda
(18, 'Free', 0.00),         -- Henry Okabe
(19, 'Obsidian', 9.99),     -- Evelyn Tsukino
(20, 'Inferno', 19.99);     -- Alexander Arata
